name: kodoja
owner: abaizan
homepage_url: https://github.com/abaizan/kodoja
remote_repository_url: https://github.com/abaizan/kodoja_galaxy
description: 'Kodoja: A workflow for virus detection in plants using k-mer analysis of RNA-sequencing data'
long_description: |
  Kodoja is a workflow for virus detection in plants using
  Kraken and Kaiju to perform k-mer analysis of RNA-sequencing.
categories:
- Sequence Analysis
type: unrestricted
include:
- LICENSE
- README.rst
- kodoja_search.xml
- test-data/kaijuDB_test/kaiju_library.fmi
- test-data/kaijuDB_test/names.dmp
- test-data/kaijuDB_test/nodes.dmp
- test-data/kaiju_databases.loc
- test-data/krakenDB_test/accmap_file.tmp
- test-data/krakenDB_test/database.idx
- test-data/krakenDB_test/database.kdb
- test-data/krakenDB_test/log_file.txt
- test-data/krakenDB_test/taxonomy/names.dmp
- test-data/krakenDB_test/taxonomy/nodes.dmp
- test-data/kraken_databases.loc
- test-data/taxonomy/names.dmp
- test-data/taxonomy/nodes.dmp
- test-data/testData_1.fasta
- test-data/testData_1.fastq
- test-data/testData_2.fasta
- test-data/testData_2.fastq
- test-data/virus_table_PE_fasta.tabular
- test-data/virus_table_PE_fastq.tabular
- test-data/virus_table_SE_fastq.tabular
- tool-data/kaiju_databases.loc.sample
- tool-data/kraken_databases.loc.sample
- tool_data_table_conf.xml.sample
- tool_data_table_conf.xml.test
- tool_data_table_conf.xml.sample
- tool_data_table_conf.xml.test
